# Generated by Django 4.2.3 on 2023-10-18 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dislikes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dislikes',
            name='video',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Dislikes',
        ),
    ]
