# Generated by Django 4.2.3 on 2023-10-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_remove_dislikes_user_remove_dislikes_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='video',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='channel',
            field=models.CharField(max_length=500),
        ),
    ]
