# Generated by Django 4.2.3 on 2023-10-19 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_likes_video_alter_subscriptions_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.videos'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel', to='db.user'),
        ),
    ]
