# Generated by Django 4.2.3 on 2023-10-19 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_likes_video_alter_subscriptions_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='description',
        ),
    ]
